hos-objs := hos_main.o hos_utils.o  regexp.o k_json.o  hos_log.o hos_client.o hos_client_fs.o 
hos-objs += hos_conntrack.o  hos_mac.o hos_config.o hos_mac_filter.o 
hos-objs += hos_app_filter.o
obj-m += hos.o
