
include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for client list
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+hosd +luci-compat
PKG_NAME:=luci-app-hosclient
PKG_VERSION:=2.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
