include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI app for hos user record
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+hosd +luci-compat +luci-lib-jsonc

PKG_NAME:=luci-app-hos-user-record
PKG_VERSION:=1.0.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature