
include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for hos macfilter
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+hosd +kmod-hos +luci-compat +luci-app-hosappfilter
PKG_NAME:=luci-app-hosmacfilter
PKG_VERSION:=2.0
PKG_RELEASE:=1
include $(TOPDIR)/feeds/luci/luci.mk
# call BuildPackage - OpenWrt buildroot signature
