
include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for hos appfilter
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+hosd +kmod-hos +luci-compat +luci-theme-hos
PKG_NAME:=luci-app-hosappfilter
PKG_VERSION:=2.0
PKG_RELEASE:=1
include $(TOPDIR)/feeds/luci/luci.mk
# call BuildPackage - OpenWrt buildroot signature
