
include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for hos feature library upgrade
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+luci-compat +luci-theme-hos
PKG_NAME:=luci-app-hosfeature
PKG_VERSION:=2.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk
# call BuildPackage - OpenWrt buildroot signature
